### ISSUE TITLE
Dependency "crypto" not working

### ISSUE THREAD

**Issue by Laurenz-M** [Mainostoimisto-Seven-1/printify-nodejs#23]
Hey everyone!
I have just installed your package via npm but I am getting an error regarding the "crypto" package that this project depends on. 
The error is as follows:

```Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.```
<img width="407" alt="image" src="https://github.com/Mainostoimisto-Seven-1/printify-nodejs/assets/88063622/3e5a5adc-e417-4dd4-94b6-fbc060619b65">
I am using the newest version of vite for my project. I am happy to provide further information if neccessary.

I suspect that this issue comes from the "crypto" package, that wa discontinued and integrated directly into nodejs as opposed to being a standalone npm package.

Cheers,
Laurenz

**Comment by Laurenz-M** [comment]
Edit: I have just removed all import references of "crypto" from the node_modules folder of the installed "printify-nodejs" package and vite started without error. Instead of explicitly importing crypto, it it now referenced globally.

//node_modules/printify-nodejs/dist/index.js
<img width="498" alt="image" src="https://github.com/Mainostoimisto-Seven-1/printify-nodejs/assets/88063622/c9aa432b-e796-4387-add7-8e7b5b7f75df">
(Removed the import and referenced "crypto" like a global class)

//node_modules/printify-nodejs/dist/index.js
<img width="431" alt="image" src="https://github.com/Mainostoimisto-Seven-1/printify-nodejs/assets/88063622/c5f17e9e-dd6f-494b-83e8-49bf6c3c6743">
(Also removed the import)

This removes all my error right now, but i am unsure if everything still works as expected. Maybe you could look into my solution :)

Cheers, 
Laurenz

**Comment by visitlo** [comment]
Removing the crypto npm dependency in pr #24 
It now *imports* the crypto package built into Node. And just to be clear, this api wrapper isn't meant to be used in the browser.
